// This file is processed by Miniswig to produce the Brux Squirrel API.
#include "api/audio.hpp"
#include "api/fileio.hpp"
#include "api/graphics.hpp"
#include "api/input.hpp"
#include "api/json.hpp"
#include "api/main.hpp"
#include "api/maths.hpp"
#include "api/sdl.hpp"
#include "api/shapes.hpp"
#include "api/sprites.hpp"
#include "api/text.hpp"
