/**
 * WARNING: This file is automatically generated from:
 *  'src/api/api.hpp'
 * DO NOT CHANGE
 */
#ifndef HEADER_BRUX_SQUIRREL_WRAPPER_HPP
#define HEADER_BRUX_SQUIRREL_WRAPPER_HPP

#include <squirrel.h>

namespace BruxAPI {

void register_brux_wrapper(HSQUIRRELVM v);


}

#endif

/* EOF */
