name: GNU/Linux (32 Bit)
on:
  push:
    branches: [ "main" ]
    paths:
      - rte/src/*
  pull_request:
    branches: [ "main" ]
    paths:
      - rte/src/*
  workflow_dispatch:

jobs:
  gnu-linux:
    strategy:
      matrix:
#        arch: [32, 64]
        arch: [32]
        build_type: [release]
        include:
          - build_type: release
            arch: 32

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install 32-bit dependencies
        if: ${{ matrix.arch == 32 }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update

          sudo apt-get install -y \
            cmake \
            build-essential \
            gcc-multilib \
            g++-multilib \
            pkgconf:i386 \
            libsdl2-dev:i386 \
            libsdl2-image-dev:i386 \
            libsdl2-mixer-dev:i386 \
            libsdl2-net-dev:i386 \
            libflac-dev:i386 \
            libjpeg-dev:i386 \
            libpng-dev:i386 \
            libtiff-dev:i386 \
            libfluidsynth-dev:i386 \
            libmodplug-dev:i386 \
            libmpg123-dev:i386 \
            libvorbis-dev:i386 \
            libopusfile-dev:i386 \
            libzstd-dev:i386 \
            libgit2-dev:i386 \
            meson

      - name: Build and install SDL2_gfx from submodule (32-bit)
        if: ${{ matrix.arch == 32 }}
        run: |
          cd rte/SDL2_gfx
          sudo mkdir -p /usr/local/include/SDL2_gfx
          # compile sources into a static lib for i386
          gcc -m32 -O2 -fPIC -I/usr/include/SDL2 -c SDL2_gfxPrimitives.c SDL2_rotozoom.c SDL2_framerate.c SDL2_imageFilter.c -I.
          ar rcs libSDL2_gfx.a *.o
          sudo cp libSDL2_gfx.a /usr/local/lib/
          sudo cp *.h /usr/local/include/
          # create a simple pkg-config file so Meson can find it via pkg-config
          cat <<'EOF' | sudo tee /usr/local/lib/pkgconfig/sdl2_gfx.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: SDL2_gfx
Description: SDL2 graphics primitives
Version: 1.0
Libs: -L${libdir} -lSDL2_gfx
Cflags: -I${includedir}
EOF
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Set compiler (gcc)
        run: |
          echo "CXX=g++" >> $GITHUB_ENV
          echo "CC=gcc" >> $GITHUB_ENV

      - name: Configure build
        env:
          ARCH: ${{ matrix.arch == 32 && '-DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32' || '' }}
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          meson --version
          $CXX --version
          cd rte
          PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/i386-linux-gnu/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig" meson setup build --cross-file crossfile/i386.cross

      - name: Build
        working-directory: rte/build
        run: |
          meson compile
          DESTDIR=bin meson install

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: "Brux-GNULinux-${{ matrix.arch }}-${{ matrix.build_type }}-binary"
          path: "rte/build/bin"
